name: build
on:
  workflow_call:
    inputs:
      java:
        type: string
        required: true
      cache:
        type: boolean
        default: true
        required: false

      gradle_tasks:
        type: string
        required: false

      reviewdog:
        type: string
        required: false

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip build]') && github.event.sender.login != 'constellation-manager[bot]'}}
    name: ${{ inputs.gradle_tasks }} build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 2
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup JDK ${{ inputs.java }}
        uses: actions/setup-java@v5.4.0
        with:
          distribution: "microsoft"
          java-version: ${{ inputs.java }}

      - name: Cache Wrapper
        if: ${{ inputs.cache == true }}
        uses: actions/cache@v6
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Cache Dependencies
        if: ${{ inputs.cache == true }}
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches/jars-*/
            ~/.gradle/caches/*/groovy-dsl/
            ~/.gradle/caches/transforms-*/
            ~/.gradle/caches/*/transforms/
            ~/.gradle/caches/modules-*/
            ~/.gradle/caches/fabric-loom/
            ~/.gradle/caches/neoformruntime/
            ~/.gradle/caches/VanillaGradle/
          key: gradle-deps-${{ hashFiles('**/gradle-wrapper.properties', '**/gradle.properties', '**/*.versions.toml', 'buildSrc/**/Versions.kt', 'buildSrc/**/Dependencies.kt', '**/versions.properties', '**/*.gradle*') }}

      - name: ${{ inputs.gradle_tasks }} build
        run: |
          ./gradlew ${{ inputs.gradle_tasks }} build publishToMavenLocal

      - name: capture build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Artifacts
          path: ~/.m2/repository/

      - name: Set up reviewdog
        if: ${{ inputs.reviewdog != '' }}
        uses: reviewdog/action-setup@v1
      - name: Upload spotbugs report
        if: ${{ inputs.reviewdog != '' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ inputs.reviewdog }}
