name: publish
on:
  workflow_call:
    inputs:
      java:
        type: string
        required: true

      version_type:
        type: string
        required: true

      publish_task:
        type: string
        default: publishMods
        required: false

    secrets:
      MODRINTH_TOKEN:
        required: false
      CURSEFORGE_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version_info: ${{ steps.get_version.outputs.version_info }}
      version_plain: ${{ steps.get_version.outputs.version_plain }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 2
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.0.0

      - name: setup jdk ${{ inputs.java }}
        uses: actions/setup-java@v4.2.2
        with:
          distribution: "microsoft"
          java-version: ${{ inputs.java }}

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Publish to Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish

      - uses: actions/create-github-app-token@v1.10.3
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}

      - name: Publish mods
        if: ${{ inputs.version_type != 'NONE' }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          VERSION_TYPE: ${{ inputs.version_type }}
        run: |
          ./gradlew ${{ inputs.publish_task }}
    
